name = "netflix-code"
main = "worker.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "TOKENS_KV", id = "93e96ba99efb45508f405affd1a3b8a4" }
]

[vars]
CODE_LIST = "1111,2222,3333"
GOOGLE_CLIENT_ID = "xxx"
GOOGLE_CLIENT_SECRET = "xxx"
GOOGLE_REDIRECT_URI = "https://netflix-code.just8n-ds.workers.dev/oauth2callback"
